FROM maven:3.6.3-openjdk-14 AS build
COPY ./ /app
WORKDIR /app
RUN mvn clean package -U

FROM adoptopenjdk:14-jre-hotspot

#Create new directory inside fs
RUN mkdir /app

#Sets working directory
WORKDIR /app

#Adds target jar to working directory
COPY --from=build ./app/api/target/image-upload-api-1.0.0-SNAPSHOT.jar  /app

#Exposes specific port to the container interface
EXPOSE 8082

CMD ["java", "-jar", "image-upload-api-1.0.0-SNAPSHOT.jar "]