kumuluzee:
  name: image-upload
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  version: 1.0.0
  server:
#    local url
#    base-url: http://localhost:8082
#    base-url: http://image-upload:8082
    base-url: http://52.191.32.66
#    base-url: http://localhost:8082   External
    http:
      port: 8082
  discovery:
    etcd:
      hosts: http://localhost:2379
  openapi:
    enabled: true
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="852bac38-fc96-4293-8c3c-78c39d020464-ls.logit.io"
                                  port="29177" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="trace" />
                                  </Root>
                              </Loggers>
                          </Configuration>'

  persistence-units:
    - name: "event-catalog-jpa"
      continue-on-error: false
azure-properties:
  azure-account-name: gojkohajdukovicstorage1
  azure-account-key:
  azure-container-name: rsoimages


