apiVersion: apps/v1
kind: Deployment
# Name of the deployment
metadata:
  name: image-upload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-upload
  template:
    metadata:
      labels:
        app: image-upload
    spec:
      containers:
        - image: ghajduk3/image-upload:latest
          name: image-upload
          env:
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: AZUREPROPERTIES_AZUREACCOUNTKEY
              valueFrom:
                secretKeyRef:
                  name: azure-acc
                  key: AZUREPROPERTIES_AZUREACCOUNTKEY
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: image-upload
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: image-upload