apiVersion: apps/v1
kind: Deployment
# Name of the deployment
metadata:
  name: image-upload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-upload
  template:
    metadata:
      labels:
        app: image-upload
    spec:
#      volumes:
#        - name: google-cloud-key
#          secret:
#            secretName: pubsub-key
      containers:
        - image: ghajduk3/image-upload:latest
          #          Pod name
          name: image-upload
          #          Here we can override environment variables
          #          env:
          #            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          #              value: jdbc:postgresql://lallah.db.elephantsql.com:5432/kryfltbl
          #            - name: KUMULUZEE_DATASOURCES0_USERNAME
          #              value: kryfltbl
          #            - name: KUMULUZEE_DATASOURCES0_PASSWORD
          #              valueFrom:
          #                secretKeyRef:
          #                  name: pg-pass
          #                  key: KUMULUZEE_DATASOURCES0_PASSWORD
#          volumeMounts:
#            - name: google-cloud-key
#              mountPath: /var/secrets/google
#          env:
#            - name: GOOGLE_APPLICATION_CREDENTIALS
#              value: /var/secrets/google/key.json
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: image-upload
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: image-upload